import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import Navbar from "../components/Navbar"; // Ensure this path is correct based on your structure

const kanit = Kanit({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin", "thai"],
  variable: "--font-kanit",
  display: "swap",
});

export const metadata: Metadata = {
  title: "PLOCLO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${kanit.variable} antialiased flex`} // Added 'flex' to body for layout
      >
        <div className="flex min-h-screen">
          {/* Sidebar */}
          <aside className="w-52 min-h-screen bg-white shadow fixed top-0 left-0">
            <Navbar />
          </aside>

          {/* Content Area */}
          <main className="flex-1 ml-50 p-6 bg-white overflow-x-auto">
            {children}
          </main>
        </div>
      </body>
    </html>
  );
}
