import type { Metadata } from "next";
import { Kanit } from "next/font/google";
import "./globals.css";
import ClientWrapper from "../components/ClientWrapper";
import I18nProvider from "../i18nProvider";
import { AuthProvider } from "../app/context/AuthContext";

const kanit = Kanit({
  weight: ["300", "400", "500", "600", "700"],
  subsets: ["latin", "thai"],
  variable: "--font-kanit",
  display: "swap",
});

export const metadata: Metadata = {
  title: "PLOCLO",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${kanit.variable} antialiased`}>
        <AuthProvider>
          <I18nProvider>
            <ClientWrapper>{children}</ClientWrapper>
          </I18nProvider>
        </AuthProvider>
      </body>
    </html>
  );
}
